-- =============================================================================
-- ESQUEMA ESTRELLA: TECNONOVA RETAIL
-- Motor objetivo: PostgreSQL 14+
-- ESTA ES LA PROPUESTA ORIGINAL DE LA IA ANTES DE LAS CORRECCIONES
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS dm_ventas;
SET search_path TO dm_ventas;

-- -----------------------------------------------------------------------------
-- Dimensiones Conformadas
-- -----------------------------------------------------------------------------

CREATE TABLE DIM_TIEMPO (
    tiempo_sk       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha           DATE NOT NULL UNIQUE,
    dia             SMALLINT NOT NULL,
    dia_semana      VARCHAR(15) NOT NULL,
    mes             SMALLINT NOT NULL,
    nombre_mes      VARCHAR(15) NOT NULL,
    trimestre       SMALLINT NOT NULL,
    anio            SMALLINT NOT NULL,
    es_fin_semana   BOOLEAN NOT NULL DEFAULT FALSE,
    es_festivo      BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO DIM_TIEMPO (tiempo_sk, fecha, dia, dia_semana, mes, nombre_mes, trimestre, anio)
VALUES (-1, '1900-01-01', 1, 'N/A', 1, 'N/A', 1, 1900);

CREATE TABLE DIM_PRODUCTO (
    producto_sk     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id     VARCHAR(20) NOT NULL UNIQUE,
    sku             VARCHAR(30) NOT NULL,
    nombre_producto VARCHAR(150) NOT NULL,
    marca           VARCHAR(60),
    categoria       VARCHAR(60),
    modelo          VARCHAR(60),
    costo_estandar  NUMERIC(12,2) CHECK (costo_estandar >= 0),
    requiere_serie  BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO DIM_PRODUCTO (producto_sk, producto_id, sku, nombre_producto)
VALUES (-1, 'N/A', 'N/A', 'No Aplica');

CREATE TABLE DIM_CLIENTE (
    cliente_sk          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id          VARCHAR(20) NOT NULL UNIQUE,
    nombre_cliente      VARCHAR(150) NOT NULL,
    tipo_cliente        VARCHAR(30),
    ciudad              VARCHAR(80),
    segmento            VARCHAR(40),
    condiciones_credito VARCHAR(100)
);

INSERT INTO DIM_CLIENTE (cliente_sk, cliente_id, nombre_cliente)
VALUES (-1, 'N/A', 'Consumidor Genérico');

CREATE TABLE DIM_SUCURSAL (
    sucursal_sk     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_id     VARCHAR(20) NOT NULL UNIQUE,
    nombre_sucursal VARCHAR(100) NOT NULL,
    ciudad          VARCHAR(80),
    region          VARCHAR(60),
    tipo_nodo       VARCHAR(30)
);

INSERT INTO DIM_SUCURSAL (sucursal_sk, sucursal_id, nombre_sucursal)
VALUES (-1, 'N/A', 'Digital / Sin Asignar');

CREATE TABLE DIM_CANAL (
    canal_sk              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canal_id              VARCHAR(20) NOT NULL UNIQUE,
    canal                 VARCHAR(40) NOT NULL,
    plataforma_origen     VARCHAR(60),
    comision_pactada_pct  NUMERIC(5,2) CHECK (comision_pactada_pct >= 0)
);

INSERT INTO DIM_CANAL (canal_sk, canal_id, canal)
VALUES (-1, 'N/A', 'No Identificado');

CREATE TABLE DIM_ASESOR (
    asesor_sk     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asesor_id     VARCHAR(20) NOT NULL UNIQUE,
    nombre_asesor VARCHAR(150) NOT NULL,
    nivel         VARCHAR(30)
);

INSERT INTO DIM_ASESOR (asesor_sk, asesor_id, nombre_asesor)
VALUES (-1, 'N/A', 'Sin Asesor');

CREATE TABLE DIM_SERVICIO (
    servicio_sk     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servicio_id     VARCHAR(20) NOT NULL UNIQUE,
    tipo_servicio   VARCHAR(40),
    nombre_servicio VARCHAR(100),
    tarifa_base     NUMERIC(12,2) CHECK (tarifa_base >= 0)
);

INSERT INTO DIM_SERVICIO (servicio_sk, servicio_id, nombre_servicio)
VALUES (-1, 'N/A', 'Sin Servicio');

CREATE TABLE DIM_METODO_PAGO (
    metodo_pago_sk  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metodo_pago_id  VARCHAR(20) NOT NULL UNIQUE,
    descripcion     VARCHAR(50) NOT NULL
);

INSERT INTO DIM_METODO_PAGO (metodo_pago_sk, metodo_pago_id, descripcion)
VALUES (-1, 'N/A', 'No Identificado');

-- -----------------------------------------------------------------------------
-- Tabla de Hechos: FACT_VENTAS
-- -----------------------------------------------------------------------------

CREATE TABLE FACT_VENTAS (
    venta_sk                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tiempo_sk                   INTEGER NOT NULL REFERENCES DIM_TIEMPO(tiempo_sk),
    producto_sk                 INTEGER NOT NULL REFERENCES DIM_PRODUCTO(producto_sk),
    servicio_sk                 INTEGER NOT NULL REFERENCES DIM_SERVICIO(servicio_sk),
    cliente_sk                  INTEGER NOT NULL REFERENCES DIM_CLIENTE(cliente_sk),
    sucursal_sk                 INTEGER NOT NULL REFERENCES DIM_SUCURSAL(sucursal_sk),
    canal_sk                    INTEGER NOT NULL REFERENCES DIM_CANAL(canal_sk),
    asesor_sk                   INTEGER NOT NULL REFERENCES DIM_ASESOR(asesor_sk),
    metodo_pago_sk              INTEGER NOT NULL REFERENCES DIM_METODO_PAGO(metodo_pago_sk),

    num_ticket                  VARCHAR(30) NOT NULL,
    num_linea                   SMALLINT NOT NULL,
    numero_serie                VARCHAR(50),
    lote_compra                 VARCHAR(30),

    cantidad                    SMALLINT NOT NULL CHECK (cantidad > 0),
    precio_unitario             NUMERIC(12,2) NOT NULL CHECK (precio_unitario >= 0),
    costo_unitario_real         NUMERIC(12,2) NOT NULL CHECK (costo_unitario_real >= 0),
    monto_bruto                 NUMERIC(14,2) NOT NULL,
    monto_descuento             NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (monto_descuento >= 0),
    monto_neto_venta            NUMERIC(14,2) NOT NULL,
    costo_total_real            NUMERIC(14,2) NOT NULL,
    margen_bruto                NUMERIC(14,2) NOT NULL,
    monto_comision_marketplace  NUMERIC(14,2) NOT NULL DEFAULT 0,
    margen_neto_real            NUMERIC(14,2) NOT NULL,

    CONSTRAINT uq_fact_ventas_ticket_linea UNIQUE (num_ticket, num_linea),
    CONSTRAINT chk_monto_bruto CHECK (monto_bruto = cantidad * precio_unitario),
    CONSTRAINT chk_monto_neto CHECK (monto_neto_venta = monto_bruto - monto_descuento),
    CONSTRAINT chk_costo_total CHECK (costo_total_real = cantidad * costo_unitario_real),
    CONSTRAINT chk_margen_bruto CHECK (margen_bruto = monto_neto_venta - costo_total_real),
    CONSTRAINT chk_margen_neto CHECK (margen_neto_real = margen_bruto - monto_comision_marketplace)
);

CREATE INDEX ix_fact_ventas_tiempo   ON FACT_VENTAS (tiempo_sk);
CREATE INDEX ix_fact_ventas_producto ON FACT_VENTAS (producto_sk);
CREATE INDEX ix_fact_ventas_cliente  ON FACT_VENTAS (cliente_sk);
CREATE INDEX ix_fact_ventas_sucursal ON FACT_VENTAS (sucursal_sk);
CREATE INDEX ix_fact_ventas_canal    ON FACT_VENTAS (canal_sk);
CREATE INDEX ix_fact_ventas_asesor   ON FACT_VENTAS (asesor_sk);

-- -----------------------------------------------------------------------------
-- Tabla de Hechos: FACT_DEVOLUCIONES
-- -----------------------------------------------------------------------------

CREATE TABLE FACT_DEVOLUCIONES (
    devolucion_sk       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tiempo_sk           INTEGER NOT NULL REFERENCES DIM_TIEMPO(tiempo_sk),
    producto_sk         INTEGER NOT NULL REFERENCES DIM_PRODUCTO(producto_sk),
    cliente_sk          INTEGER NOT NULL REFERENCES DIM_CLIENTE(cliente_sk),
    sucursal_sk         INTEGER NOT NULL REFERENCES DIM_SUCURSAL(sucursal_sk),

    num_devolucion      VARCHAR(30) NOT NULL UNIQUE,
    ticket_venta_origen VARCHAR(30) NOT NULL,
    numero_serie        VARCHAR(50),
    motivo_devolucion   VARCHAR(100) NOT NULL,

    cantidad_devuelta   SMALLINT NOT NULL CHECK (cantidad_devuelta > 0),
    monto_devolucion    NUMERIC(14,2) NOT NULL CHECK (monto_devolucion >= 0)
);

CREATE INDEX ix_fact_devol_tiempo   ON FACT_DEVOLUCIONES (tiempo_sk);
CREATE INDEX ix_fact_devol_producto ON FACT_DEVOLUCIONES (producto_sk);
CREATE INDEX ix_fact_devol_sucursal ON FACT_DEVOLUCIONES (sucursal_sk);
CREATE INDEX ix_fact_devol_origen   ON FACT_DEVOLUCIONES (ticket_venta_origen);

-- -----------------------------------------------------------------------------
-- Tabla de Hechos: FACT_STOCK
-- -----------------------------------------------------------------------------

CREATE TABLE FACT_STOCK (
    tiempo_sk               INTEGER NOT NULL REFERENCES DIM_TIEMPO(tiempo_sk),
    sucursal_sk             INTEGER NOT NULL REFERENCES DIM_SUCURSAL(sucursal_sk),
    producto_sk             INTEGER NOT NULL REFERENCES DIM_PRODUCTO(producto_sk),
    cantidad_disponible     INTEGER NOT NULL CHECK (cantidad_disponible >= 0),
    cantidad_apartada       INTEGER NOT NULL DEFAULT 0 CHECK (cantidad_apartada >= 0),
    costo_inventario_total  NUMERIC(14,2) NOT NULL CHECK (costo_inventario_total >= 0),
    PRIMARY KEY (tiempo_sk, sucursal_sk, producto_sk)
);

CREATE INDEX ix_fact_stock_producto ON FACT_STOCK (producto_sk);
CREATE INDEX ix_fact_stock_sucursal ON FACT_STOCK (sucursal_sk);
