-- =============================================================================
-- PROYECTO: DATA MART DE VENTAS Y RENTABILIDAD · TECNONOVA RETAIL
-- CASO: Caso 2 - Retail TecnoNova (U2)
-- MOTOR OBJETIVO: PostgreSQL 14+ / ANSI SQL
-- Implementación Física DDL del Esquema Dimensional
-- =============================================================================
--
-- MEMORIA DE ARQUITECTURA Y DELIMITACIÓN DE ALCANCE:
--
-- 1. DELIMITACIÓN ESTRICTA DEL ALCANCE (OLAP vs. OLTP):
--    Este script implementa EXCLUSIVAMENTE la capa dimensional (tablas DIM_ y FACT_).
--    Las entidades 'PAGO_VENTA' y 'METODO_PAGO' pertenecen funcionalmente al modelo
--    relacional operacional/transaccional en 3NF (Entregable 2), donde resuelven la 
--    Primera Forma Normal (1NF) para apartados y anticipos (Regla #3).
--    En este Data Mart se omiten deliberadamente para prevenir la trampa de abanico 
--    (Fan Trap) en el grano de línea de producto; el seguimiento de saldos y abonos 
--    se delega a un Data Mart satélite de Tesorería.
--
-- 2. POLÍTICA DE INTEGRIDAD Y CERO NULOS (Zero-NULL Foreign Key Policy):
--    En apego a la metodología de Ralph Kimball, se prohíbe el uso de NULL en llaves 
--    foráneas dentro de las tablas de hechos. Cada una de las 7 dimensiones conformadas 
--    incluye un registro centinela con clave sustituta SK = -1 ('No aplica / Desconocido').
--    Esto previene la exclusión silenciosa de métricas al ejecutar INNER JOINs en 
--    herramientas de Business Intelligence (Power BI, Tableau) y resuelve escenarios 
--    como ventas de autoservicio digital (sin asesor) o ventas de servicios puros (sin hardware).
--
-- 3. RESOLUCIÓN DE REGLAS DE NEGOCIO EN CAPA ETL:
--    - Regla #5 (Precios según método de pago y promociones): Las variaciones monetarias 
--      por instrumento de cobro (descuentos en efectivo o recargos por tarjeta) se 
--      absorben y liquidan durante el pipeline de extracción/transformación (ETL) a nivel 
--      atómico dentro de 'precio_unitario' y 'monto_descuento'.
--    - Hito contable de apartados: La tabla FACT_VENTAS únicamente captura ventas 
--      liquidadas y formalmente entregadas. Los productos en proceso de abono se auditan 
--      en la métrica 'cantidad_apartada' de FACT_STOCK.
--
-- 4. PREPARACIÓN ARQUITECTÓNICA DE INVENTARIO:
--    La tabla FACT_STOCK se incluye formalmente bajo el patrón 'Periodic Snapshot' 
--    para viabilizar el cálculo de rotación financiera requerido por la dirección, 
--    documentando que recibirá cargas cuando se integre el sistema de almacenes (WMS).
-- =============================================================================

-- Creación y configuración del esquema lógico analítico
CREATE SCHEMA IF NOT EXISTS dm_ventas;
SET search_path TO dm_ventas;

-- Limpieza preventiva en orden inverso de dependencias
DROP TABLE IF EXISTS FACT_STOCK CASCADE;
DROP TABLE IF EXISTS FACT_DEVOLUCIONES CASCADE;
DROP TABLE IF EXISTS FACT_VENTAS CASCADE;
DROP TABLE IF EXISTS DIM_SERVICIO CASCADE;
DROP TABLE IF EXISTS DIM_ASESOR CASCADE;
DROP TABLE IF EXISTS DIM_CANAL CASCADE;
DROP TABLE IF EXISTS DIM_SUCURSAL CASCADE;
DROP TABLE IF EXISTS DIM_CLIENTE CASCADE;
DROP TABLE IF EXISTS DIM_PRODUCTO CASCADE;
DROP TABLE IF EXISTS DIM_TIEMPO CASCADE;

-- =============================================================================
-- SECCIÓN 1: DIMENSIONES CONFORMADAS (Conformed Dimensions)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1.1 DIM_TIEMPO
-- Grano: Un día calendario.
-- Justificación: Desacopla la marca temporal en jerarquías analíticas para evaluar 
-- estacionalidad, comportamiento en fines de semana y festivos.
-- -----------------------------------------------------------------------------
CREATE TABLE DIM_TIEMPO (
    tiempo_sk       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha           DATE        NOT NULL,
    dia             SMALLINT    NOT NULL,
    dia_semana      VARCHAR(15) NOT NULL,
    mes             SMALLINT    NOT NULL,
    nombre_mes      VARCHAR(15) NOT NULL,
    trimestre       SMALLINT    NOT NULL,
    anio            SMALLINT    NOT NULL,
    es_fin_semana   BOOLEAN     NOT NULL DEFAULT FALSE,
    es_festivo      BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_dim_tiempo_fecha UNIQUE (fecha)
);

COMMENT ON TABLE DIM_TIEMPO IS 
    'Dimensión de tiempo conformada. Generada algorítmicamente para análisis de series históricas y estacionalidad.';
COMMENT ON COLUMN DIM_TIEMPO.tiempo_sk IS 
    'Surrogate Key del calendario. -1 = Fecha no definida o en trámite.';

-- Registro centinela para blindaje ante fechas no identificadas
INSERT INTO DIM_TIEMPO (tiempo_sk, fecha, dia, dia_semana, mes, nombre_mes, trimestre, anio, es_fin_semana, es_festivo)
VALUES (-1, DATE '1900-01-01', 1, 'No Definido', 1, 'No Definido', 1, 1900, FALSE, FALSE);

-- -----------------------------------------------------------------------------
-- 1.2 DIM_PRODUCTO
-- Grano: Un artículo o SKU del catálogo de hardware.
-- Justificación: Permite analizar la rentabilidad por marca, modelo y categoría. 
-- El atributo 'requiere_serie' implementa formalmente la Regla de Negocio #2.
-- -----------------------------------------------------------------------------
CREATE TABLE DIM_PRODUCTO (
    producto_sk     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id     VARCHAR(20)  NOT NULL, -- Llave natural en sistema transaccional
    sku             VARCHAR(30)  NOT NULL,
    nombre_producto VARCHAR(150) NOT NULL,
    marca           VARCHAR(60),
    categoria       VARCHAR(60),
    modelo          VARCHAR(60),
    costo_estandar  NUMERIC(12,2) CHECK (costo_estandar >= 0),
    requiere_serie  BOOLEAN      NOT NULL DEFAULT FALSE, -- Regla #2: Control de series
    CONSTRAINT uq_dim_producto_id UNIQUE (producto_id)
);

COMMENT ON TABLE DIM_PRODUCTO IS 
    'Catálogo maestro de hardware. Responde a ventas, márgenes brutos y mermas por marca, modelo y categoría.';
COMMENT ON COLUMN DIM_PRODUCTO.producto_sk IS 
    'Surrogate Key. -1 = Transacción de servicio puro o póliza sin hardware.';
COMMENT ON COLUMN DIM_PRODUCTO.requiere_serie IS 
    'Bandera operativa para hardware delicado que exige número de serie unitario (Regla #2).';

-- Registro centinela para ventas exclusivas de servicios intangibles
INSERT INTO DIM_PRODUCTO (producto_sk, producto_id, sku, nombre_producto, marca, categoria, modelo, costo_estandar, requiere_serie)
VALUES (-1, 'N/A', 'N/A', 'Sin Producto (Renglón de Servicio Puro)', 'No Aplica', 'Servicios', 'No Aplica', 0.00, FALSE);

-- -----------------------------------------------------------------------------
-- 1.3 DIM_CLIENTE
-- Grano: Un cliente registrado o persona jurídica.
-- Justificación: Segmenta el mercado entre consumidor final y empresas. 
-- El atributo 'condiciones_credito' modela el supuesto de la Regla #8 (B2B).
-- -----------------------------------------------------------------------------
CREATE TABLE DIM_CLIENTE (
    cliente_sk          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id          VARCHAR(20)  NOT NULL, -- Llave natural
    nombre_cliente      VARCHAR(150) NOT NULL,
    tipo_cliente        VARCHAR(30),           -- Consumidor Final, Estudiante, Empresa
    ciudad              VARCHAR(80),
    segmento            VARCHAR(40),           -- Retail, Corporativo, Gobierno
    condiciones_credito VARCHAR(100),          -- Regla #8: Términos comerciales B2B
    CONSTRAINT uq_dim_cliente_id UNIQUE (cliente_id)
);

COMMENT ON TABLE DIM_CLIENTE IS 
    'Dimensión de clientes. Permite contrastar compras minoristas contra pedidos empresariales B2B.';
COMMENT ON COLUMN DIM_CLIENTE.cliente_sk IS 
    'Surrogate Key. -1 = Venta de mostrador a consumidor anónimo / no identificado.';
COMMENT ON COLUMN DIM_CLIENTE.condiciones_credito IS 
    'Supuesto de diseño documentado para soportar plazos y créditos comerciales (Regla #8).';

-- Registro centinela para clientes genéricos de mostrador
INSERT INTO DIM_CLIENTE (cliente_sk, cliente_id, nombre_cliente, tipo_cliente, ciudad, segmento, condiciones_credito)
VALUES (-1, 'N/A', 'Consumidor Genérico / No Identificado', 'Consumidor Final', 'Desconocida', 'Retail', 'Contado');

-- -----------------------------------------------------------------------------
-- 1.4 DIM_SUCURSAL
-- Grano: Un punto de venta físico, almacén regional o nodo logístico.
-- Justificación: Responde a la rotación geográfica y compara tiendas vs. centros 
-- de distribución (12 tiendas físicas + 1 Centro de Distribución).
-- -----------------------------------------------------------------------------
CREATE TABLE DIM_SUCURSAL (
    sucursal_sk     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_id     VARCHAR(20)  NOT NULL, -- Llave natural
    nombre_sucursal VARCHAR(100) NOT NULL,
    ciudad          VARCHAR(80),
    region          VARCHAR(60),
    tipo_nodo       VARCHAR(30),           -- Tienda Física, Hub Logístico, Digital
    CONSTRAINT uq_dim_sucursal_id UNIQUE (sucursal_id)
);

COMMENT ON TABLE DIM_SUCURSAL IS 
    'Nodos operativos de TecnoNova. Clasifica puntos de venta físicos y centros logísticos de despacho.';
COMMENT ON COLUMN DIM_SUCURSAL.sucursal_sk IS 
    'Surrogate Key. -1 = Venta digital remota sin adscripción a tienda física.';

-- Registro centinela para ventas puramente digitales
INSERT INTO DIM_SUCURSAL (sucursal_sk, sucursal_id, nombre_sucursal, ciudad, region, tipo_nodo)
VALUES (-1, 'N/A', 'Sin Sucursal Asignada / Despacho Central Digital', 'No Aplica', 'Nacional', 'Digital');

-- -----------------------------------------------------------------------------
-- 1.5 DIM_CANAL
-- Grano: Un canal comercial o plataforma de venta.
-- Justificación: Habilita el cálculo y contraste de comisiones de intermediarios 
-- digitales (Amazon, MercadoLibre) frente al canal web propio y piso de venta.
-- -----------------------------------------------------------------------------
CREATE TABLE DIM_CANAL (
    canal_sk              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canal_id              VARCHAR(20) NOT NULL, -- Llave natural
    canal                 VARCHAR(40) NOT NULL, -- Tienda física, E-commerce, Marketplace
    plataforma_origen     VARCHAR(60),          -- Amazon, MercadoLibre, Portal Web, Mostrador
    comision_pactada_pct  NUMERIC(5,2) CHECK (comision_pactada_pct >= 0),
    CONSTRAINT uq_dim_canal_id UNIQUE (canal_id)
);

COMMENT ON TABLE DIM_CANAL IS 
    'Clasificación omnicanal de TecnoNova y parametrización de comisiones de intermediarios.';
COMMENT ON COLUMN DIM_CANAL.canal_sk IS 
    'Surrogate Key. -1 = Canal de venta no clasificado o desconocido.';

-- Registro centinela
INSERT INTO DIM_CANAL (canal_sk, canal_id, canal, plataforma_origen, comision_pactada_pct)
VALUES (-1, 'N/A', 'Canal No Identificado', 'Desconocido', 0.00);

-- -----------------------------------------------------------------------------
-- 1.6 DIM_ASESOR
-- Grano: Un ejecutivo de venta o asesor de piso.
-- Justificación: Permite evaluar la productividad y ticket promedio de la fuerza 
-- de ventas asistida frente a ventas de autoservicio en plataformas web.
-- -----------------------------------------------------------------------------
CREATE TABLE DIM_ASESOR (
    asesor_sk     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asesor_id     VARCHAR(20)  NOT NULL, -- Llave natural (nómina)
    nombre_asesor VARCHAR(150) NOT NULL,
    nivel         VARCHAR(30),           -- Junior, Senior, Especialista
    CONSTRAINT uq_dim_asesor_id UNIQUE (asesor_id)
);

COMMENT ON TABLE DIM_ASESOR IS 
    'Fuerza comercial interna. Habilita análisis de desempeño individual y comisiones por venta asistida.';
COMMENT ON COLUMN DIM_ASESOR.asesor_sk IS 
    'Surrogate Key. -1 = Venta no asistida / Autoservicio web / Marketplace.';

-- Registro centinela para ventas sin vendedor
INSERT INTO DIM_ASESOR (asesor_sk, asesor_id, nombre_asesor, nivel)
VALUES (-1, 'N/A', 'Sin Asesor (Venta Autoservicio / Digital)', 'No Aplica');

-- -----------------------------------------------------------------------------
-- 1.7 DIM_SERVICIO
-- Grano: Una póliza de servicio, mantenimiento o extensión de garantía.
-- Justificación: Aísla el catálogo de intangibles para calcular el índice de 
-- penetración cruzada (Attach Rate) sobre las ventas de hardware.
-- -----------------------------------------------------------------------------
CREATE TABLE DIM_SERVICIO (
    servicio_sk     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servicio_id     VARCHAR(20)  NOT NULL, -- Llave natural
    tipo_servicio   VARCHAR(40),           -- Garantía Extendida, Mantenimiento, Configuración
    nombre_servicio VARCHAR(100),
    tarifa_base     NUMERIC(12,2) CHECK (tarifa_base >= 0),
    CONSTRAINT uq_dim_servicio_id UNIQUE (servicio_id)
);

COMMENT ON TABLE DIM_SERVICIO IS 
    'Catálogo de pólizas y servicios. Utilizada para monitorear ingresos por garantías extendidas.';
COMMENT ON COLUMN DIM_SERVICIO.servicio_sk IS 
    'Surrogate Key. -1 = Renglón de venta de producto físico puro (sin póliza de servicio).';

-- Registro centinela para ventas de hardware sin servicio
INSERT INTO DIM_SERVICIO (servicio_sk, servicio_id, tipo_servicio, nombre_servicio, tarifa_base)
VALUES (-1, 'N/A', 'No Aplica', 'Sin Servicio (Venta de Hardware Puro)', 0.00);

-- =============================================================================
-- SECCIÓN 2: TABLAS DE HECHOS (Fact Tables)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 2.1 FACT_VENTAS
-- Grano: Un renglón o ítem individual facturado dentro de una transacción liquidada.
-- Llaves de Grano: venta_sk (PK técnica) y la pareja (num_ticket, num_linea) UNIQUE.
-- Hito de Realización: Se carga únicamente cuando la venta ha sido liquidada y entregada.
-- -----------------------------------------------------------------------------
CREATE TABLE FACT_VENTAS (
    -- Surrogate key física del hecho (optimización de direccionamiento e indexación en PG)
    venta_sk                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Llaves foráneas a dimensiones conformadas (Garantía de Cero Nulos)
    tiempo_sk                   INTEGER NOT NULL REFERENCES DIM_TIEMPO(tiempo_sk),
    producto_sk                 INTEGER NOT NULL REFERENCES DIM_PRODUCTO(producto_sk),
    servicio_sk                 INTEGER NOT NULL REFERENCES DIM_SERVICIO(servicio_sk),
    cliente_sk                  INTEGER NOT NULL REFERENCES DIM_CLIENTE(cliente_sk),
    sucursal_sk                 INTEGER NOT NULL REFERENCES DIM_SUCURSAL(sucursal_sk),
    canal_sk                    INTEGER NOT NULL REFERENCES DIM_CANAL(canal_sk),
    asesor_sk                   INTEGER NOT NULL REFERENCES DIM_ASESOR(asesor_sk),

    -- Dimensiones degeneradas (Atributos de auditoría sin tabla satélite)
    num_ticket                  VARCHAR(30)  NOT NULL,
    num_linea                   SMALLINT     NOT NULL,
    numero_serie                VARCHAR(50), -- Capturado si DIM_PRODUCTO.requiere_serie = TRUE
    lote_compra                 VARCHAR(30), -- Regla #7: Trazabilidad de costos por lote de compra
    tiene_garantia_extendida    BOOLEAN      NOT NULL DEFAULT FALSE, -- Flag para cálculo instantáneo de Attach Rate

    -- Métricas cuantitativas almacenadas
    cantidad                    SMALLINT      NOT NULL CHECK (cantidad > 0),
    precio_unitario             NUMERIC(12,2) NOT NULL CHECK (precio_unitario >= 0),   -- No aditiva
    costo_unitario_real         NUMERIC(12,2) NOT NULL CHECK (costo_unitario_real >= 0), -- No aditiva (Costo real de lote)
    monto_bruto                 NUMERIC(14,2) NOT NULL,   -- Aditiva: cantidad * precio_unitario
    monto_descuento             NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (monto_descuento >= 0), -- Aditiva
    monto_neto_venta            NUMERIC(14,2) NOT NULL,   -- Aditiva: monto_bruto - monto_descuento
    costo_total_real            NUMERIC(14,2) NOT NULL,   -- Aditiva: cantidad * costo_unitario_real
    margen_bruto                NUMERIC(14,2) NOT NULL,   -- Aditiva: monto_neto_venta - costo_total_real
    monto_comision_marketplace  NUMERIC(14,2) NOT NULL DEFAULT 0, -- Aditiva: Deducción contractual de intermediario
    margen_neto_real            NUMERIC(14,2) NOT NULL,   -- Aditiva: margen_bruto - monto_comision_marketplace

    -- Restricciones de integridad relacional y consistencia matemática
    CONSTRAINT uq_fact_ventas_ticket_linea UNIQUE (num_ticket, num_linea),
    CONSTRAINT chk_monto_bruto  CHECK (monto_bruto = cantidad * precio_unitario),
    CONSTRAINT chk_monto_neto   CHECK (monto_neto_venta = monto_bruto - monto_descuento),
    CONSTRAINT chk_costo_total  CHECK (costo_total_real = cantidad * costo_unitario_real),
    CONSTRAINT chk_margen_bruto CHECK (margen_bruto = monto_neto_venta - costo_total_real),
    CONSTRAINT chk_margen_neto  CHECK (margen_neto_real = margen_bruto - monto_comision_marketplace)
);

COMMENT ON TABLE FACT_VENTAS IS 
    'Hecho transaccional principal. Grano atómico a nivel de renglón facturado de venta liquidada y entregada.';
COMMENT ON COLUMN FACT_VENTAS.tiene_garantia_extendida IS 
    'Bandera analítica desnormalizada. Evita auto-joins reflexivos para computar el Attach Rate.';
COMMENT ON COLUMN FACT_VENTAS.costo_unitario_real IS 
    'Costo real de adquisición del lote vendido (Regla #7), superando costos estándar teóricos.';
COMMENT ON COLUMN FACT_VENTAS.monto_comision_marketplace IS 
    'Monto monetario de comisión retenido por plataformas digitales de intermediación (Amazon, ML).';

-- Índices B-Tree dedicados sobre llaves foráneas para evitar escaneos secuenciales (Full Table Scans)
CREATE INDEX ix_fact_ventas_tiempo   ON FACT_VENTAS USING BTREE (tiempo_sk);
CREATE INDEX ix_fact_ventas_producto ON FACT_VENTAS USING BTREE (producto_sk);
CREATE INDEX ix_fact_ventas_servicio ON FACT_VENTAS USING BTREE (servicio_sk);
CREATE INDEX ix_fact_ventas_cliente  ON FACT_VENTAS USING BTREE (cliente_sk);
CREATE INDEX ix_fact_ventas_sucursal ON FACT_VENTAS USING BTREE (sucursal_sk);
CREATE INDEX ix_fact_ventas_canal    ON FACT_VENTAS USING BTREE (canal_sk);
CREATE INDEX ix_fact_ventas_asesor   ON FACT_VENTAS USING BTREE (asesor_sk);
CREATE INDEX ix_fact_ventas_garantia ON FACT_VENTAS USING BTREE (tiene_garantia_extendida);

-- -----------------------------------------------------------------------------
-- 2.2 FACT_DEVOLUCIONES
-- Grano: Un evento de reclamo, retorno físico o reembolso procesado para un ítem.
-- Trazabilidad: Mantiene acoplamiento atómico exacto 1:1 con la PK compuesta de 
-- FACT_VENTAS a través de (ticket_venta_origen, linea_venta_origen).
-- -----------------------------------------------------------------------------
CREATE TABLE FACT_DEVOLUCIONES (
    devolucion_sk       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Llaves foráneas a dimensiones conformadas
    tiempo_sk           INTEGER NOT NULL REFERENCES DIM_TIEMPO(tiempo_sk),
    producto_sk         INTEGER NOT NULL REFERENCES DIM_PRODUCTO(producto_sk),
    cliente_sk          INTEGER NOT NULL REFERENCES DIM_CLIENTE(cliente_sk),
    sucursal_sk         INTEGER NOT NULL REFERENCES DIM_SUCURSAL(sucursal_sk), -- Sucursal receptora del reclamo

    -- Dimensiones degeneradas de control y enlace atómico
    num_devolucion      VARCHAR(30)  NOT NULL,
    ticket_venta_origen VARCHAR(30)  NOT NULL,
    linea_venta_origen  SMALLINT     NOT NULL DEFAULT 1, -- Cruce exacto con FACT_VENTAS.num_linea
    numero_serie        VARCHAR(50),
    motivo_devolucion   VARCHAR(100) NOT NULL,

    -- Métricas cuantitativas
    cantidad_devuelta   SMALLINT     NOT NULL CHECK (cantidad_devuelta > 0),
    monto_devolucion    NUMERIC(14,2) NOT NULL CHECK (monto_devolucion >= 0),

    CONSTRAINT uq_fact_devoluciones_num UNIQUE (num_devolucion)
);

COMMENT ON TABLE FACT_DEVOLUCIONES IS 
    'Hecho transaccional de posventa. Monitorea retornos físicos, causas de falla y notas de crédito generadas.';
COMMENT ON COLUMN FACT_DEVOLUCIONES.linea_venta_origen IS 
    'Identificador del renglón original facturado. Garantiza acoplamiento unívoco con FACT_VENTAS(num_ticket, num_linea).';
COMMENT ON COLUMN FACT_DEVOLUCIONES.sucursal_sk IS 
    'Supuesto ETL: Sucursal receptora del hardware devuelto (capturada por POS o heredada de la venta).';

-- Índices B-Tree para optimización de agregaciones de posventa y auditoría cruzada
CREATE INDEX ix_fact_devol_tiempo   ON FACT_DEVOLUCIONES USING BTREE (tiempo_sk);
CREATE INDEX ix_fact_devol_producto ON FACT_DEVOLUCIONES USING BTREE (producto_sk);
CREATE INDEX ix_fact_devol_cliente  ON FACT_DEVOLUCIONES USING BTREE (cliente_sk);
CREATE INDEX ix_fact_devol_sucursal ON FACT_DEVOLUCIONES USING BTREE (sucursal_sk);
CREATE INDEX ix_fact_devol_origen   ON FACT_DEVOLUCIONES USING BTREE (ticket_venta_origen, linea_venta_origen);

-- -----------------------------------------------------------------------------
-- 2.3 FACT_STOCK
-- Grano: Instantánea periódica (Periodic Snapshot) mensual/diaria por tiempo, sucursal y producto.
-- Justificación: PREPARACIÓN ARQUITECTÓNICA. En el caso oficial no se entregó fuente de 
-- almacén, pero se incluye formalmente para sustentar la fórmula de rotación financiera:
-- Rotación = SUM(FACT_VENTAS[costo_total_real]) / PROMEDIO(FACT_STOCK[costo_inventario_total]).
-- -----------------------------------------------------------------------------
CREATE TABLE FACT_STOCK (
    tiempo_sk               INTEGER NOT NULL REFERENCES DIM_TIEMPO(tiempo_sk),
    sucursal_sk             INTEGER NOT NULL REFERENCES DIM_SUCURSAL(sucursal_sk),
    producto_sk             INTEGER NOT NULL REFERENCES DIM_PRODUCTO(producto_sk),

    -- Métricas semi-aditivas (sumables en productos y tiendas, no sumables en el tiempo)
    cantidad_disponible     INTEGER NOT NULL CHECK (cantidad_disponible >= 0),
    cantidad_apartada       INTEGER NOT NULL DEFAULT 0 CHECK (cantidad_apartada >= 0), -- Mercancía comprometida por apartados (Regla #3)
    costo_inventario_total  NUMERIC(14,2) NOT NULL CHECK (costo_inventario_total >= 0), -- Existencias valorizadas

    PRIMARY KEY (tiempo_sk, sucursal_sk, producto_sk)
);

COMMENT ON TABLE FACT_STOCK IS 
    'Estructura preparatoria de Periodic Snapshot. Suministra el inventario promedio indispensable para la rotación.';
COMMENT ON COLUMN FACT_STOCK.cantidad_apartada IS 
    'Monitorea el inventario retenido por órdenes con abonos pendientes antes de su entrega definitiva.';

-- Índices secundarios para acelerar consultas analíticas filtradas por producto o sucursal
CREATE INDEX ix_fact_stock_producto ON FACT_STOCK USING BTREE (producto_sk);
CREATE INDEX ix_fact_stock_sucursal ON FACT_STOCK USING BTREE (sucursal_sk);

-- =============================================================================
-- FIN DEL SCRIPT DDL · TECNONOVA RETAIL
-- =============================================================================
